INSERT INTO continents (name) VALUES ('Africa');
INSERT INTO continents (name) VALUES ('Asia');
INSERT INTO continents (name) VALUES ('Europe');
INSERT INTO continents (name) VALUES ('North America');
INSERT INTO continents (name) VALUES ('Oceania');
INSERT INTO continents (name) VALUES ('South America');
INSERT INTO countries (name, continent_id) VALUES ('Algeria', '1');
INSERT INTO countries (name, continent_id) VALUES ('Angola', '1');
INSERT INTO countries (name, continent_id) VALUES ('Benin', '1');
INSERT INTO countries (name, continent_id) VALUES ('Botswana', '1');
INSERT INTO countries (name, continent_id) VALUES ('Burkina', '1');
INSERT INTO countries (name, continent_id) VALUES ('Burundi', '1');
INSERT INTO countries (name, continent_id) VALUES ('Cameroon', '1');
INSERT INTO countries (name, continent_id) VALUES ('Cape Verde', '1');
INSERT INTO countries (name, continent_id) VALUES ('Central African Republic', '1');
INSERT INTO countries (name, continent_id) VALUES ('Chad', '1');
INSERT INTO countries (name, continent_id) VALUES ('Comoros', '1');
INSERT INTO countries (name, continent_id) VALUES ('Congo', '1');
INSERT INTO countries (name, continent_id) VALUES ('Democratic Republic of Congo', '1');
INSERT INTO countries (name, continent_id) VALUES ('Djibouti', '1');
INSERT INTO countries (name, continent_id) VALUES ('Egypt', '1');
INSERT INTO countries (name, continent_id) VALUES ('Equatorial Guinea', '1');
INSERT INTO countries (name, continent_id) VALUES ('Eritrea', '1');
INSERT INTO countries (name, continent_id) VALUES ('Ethiopia', '1');
INSERT INTO countries (name, continent_id) VALUES ('Gabon', '1');
INSERT INTO countries (name, continent_id) VALUES ('Gambia', '1');
INSERT INTO countries (name, continent_id) VALUES ('Ghana', '1');
INSERT INTO countries (name, continent_id) VALUES ('Guinea', '1');
INSERT INTO countries (name, continent_id) VALUES ('Guinea-Bissau', '1');
INSERT INTO countries (name, continent_id) VALUES ('Ivory Coast', '1');
INSERT INTO countries (name, continent_id) VALUES ('Kenya', '1');
INSERT INTO countries (name, continent_id) VALUES ('Lesotho', '1');
INSERT INTO countries (name, continent_id) VALUES ('Liberia', '1');
INSERT INTO countries (name, continent_id) VALUES ('Libya', '1');
INSERT INTO countries (name, continent_id) VALUES ('Madagascar', '1');
INSERT INTO countries (name, continent_id) VALUES ('Malawi', '1');
INSERT INTO countries (name, continent_id) VALUES ('Mali', '1');
INSERT INTO countries (name, continent_id) VALUES ('Mauritania', '1');
INSERT INTO countries (name, continent_id) VALUES ('Mauritius', '1');
INSERT INTO countries (name, continent_id) VALUES ('Morocco', '1');
INSERT INTO countries (name, continent_id) VALUES ('Mozambique', '1');
INSERT INTO countries (name, continent_id) VALUES ('Namibia', '1');
INSERT INTO countries (name, continent_id) VALUES ('Niger', '1');
INSERT INTO countries (name, continent_id) VALUES ('Nigeria', '1');
INSERT INTO countries (name, continent_id) VALUES ('Rwanda', '1');
INSERT INTO countries (name, continent_id) VALUES ('Sao Tome and Principe', '1');
INSERT INTO countries (name, continent_id) VALUES ('Senegal', '1');
INSERT INTO countries (name, continent_id) VALUES ('Seychelles', '1');
INSERT INTO countries (name, continent_id) VALUES ('Sierra Leone', '1');
INSERT INTO countries (name, continent_id) VALUES ('Somalia', '1');
INSERT INTO countries (name, continent_id) VALUES ('South Africa', '1');
INSERT INTO countries (name, continent_id) VALUES ('South Sudan', '1');
INSERT INTO countries (name, continent_id) VALUES ('Sudan', '1');
INSERT INTO countries (name, continent_id) VALUES ('Swaziland', '1');
INSERT INTO countries (name, continent_id) VALUES ('Tanzania', '1');
INSERT INTO countries (name, continent_id) VALUES ('Togo', '1');
INSERT INTO countries (name, continent_id) VALUES ('Tunisia', '1');
INSERT INTO countries (name, continent_id) VALUES ('Uganda', '1');
INSERT INTO countries (name, continent_id) VALUES ('Zambia', '1');
INSERT INTO countries (name, continent_id) VALUES ('Zimbabwe', '1');
INSERT INTO countries (name, continent_id) VALUES ('Afghanistan', '2');
INSERT INTO countries (name, continent_id) VALUES ('Bahrain', '2');
INSERT INTO countries (name, continent_id) VALUES ('Bangladesh', '2');
INSERT INTO countries (name, continent_id) VALUES ('Bhutan', '2');
INSERT INTO countries (name, continent_id) VALUES ('Brunei', '2');
INSERT INTO countries (name, continent_id) VALUES ('Burma (Myanmar)', '2');
INSERT INTO countries (name, continent_id) VALUES ('Cambodia', '2');
INSERT INTO countries (name, continent_id) VALUES ('China', '2');
INSERT INTO countries (name, continent_id) VALUES ('East Timor', '2');
INSERT INTO countries (name, continent_id) VALUES ('Hong Kong', '2');
INSERT INTO countries (name, continent_id) VALUES ('India', '2');
INSERT INTO countries (name, continent_id) VALUES ('Indonesia', '2');
INSERT INTO countries (name, continent_id) VALUES ('Iran', '2');
INSERT INTO countries (name, continent_id) VALUES ('Iraq', '2');
INSERT INTO countries (name, continent_id) VALUES ('Israel', '2');
INSERT INTO countries (name, continent_id) VALUES ('Japan', '2');
INSERT INTO countries (name, continent_id) VALUES ('Jordan', '2');
INSERT INTO countries (name, continent_id) VALUES ('Kazakhstan', '2');
INSERT INTO countries (name, continent_id) VALUES ('North Korea', '2');
INSERT INTO countries (name, continent_id) VALUES ('South Korea', '2');
INSERT INTO countries (name, continent_id) VALUES ('Kuwait', '2');
INSERT INTO countries (name, continent_id) VALUES ('Kyrgyzstan', '2');
INSERT INTO countries (name, continent_id) VALUES ('Laos', '2');
INSERT INTO countries (name, continent_id) VALUES ('Lebanon', '2');
INSERT INTO countries (name, continent_id) VALUES ('Malaysia', '2');
INSERT INTO countries (name, continent_id) VALUES ('Maldives', '2');
INSERT INTO countries (name, continent_id) VALUES ('Mongolia', '2');
INSERT INTO countries (name, continent_id) VALUES ('Nepal', '2');
INSERT INTO countries (name, continent_id) VALUES ('Oman', '2');
INSERT INTO countries (name, continent_id) VALUES ('Pakistan', '2');
INSERT INTO countries (name, continent_id) VALUES ('Philippines', '2');
INSERT INTO countries (name, continent_id) VALUES ('Qatar', '2');
INSERT INTO countries (name, continent_id) VALUES ('Russia', '2');
INSERT INTO countries (name, continent_id) VALUES ('Saudi Arabia', '2');
INSERT INTO countries (name, continent_id) VALUES ('Singapore', '2');
INSERT INTO countries (name, continent_id) VALUES ('Sri Lanka', '2');
INSERT INTO countries (name, continent_id) VALUES ('Syria', '2');
INSERT INTO countries (name, continent_id) VALUES ('Taiwan', '2');
INSERT INTO countries (name, continent_id) VALUES ('Tajikistan', '2');
INSERT INTO countries (name, continent_id) VALUES ('Thailand', '2');
INSERT INTO countries (name, continent_id) VALUES ('Turkmenistan', '2');
INSERT INTO countries (name, continent_id) VALUES ('United Arab Emirates', '2');
INSERT INTO countries (name, continent_id) VALUES ('Uzbekistan', '2');
INSERT INTO countries (name, continent_id) VALUES ('Vietnam', '2');
INSERT INTO countries (name, continent_id) VALUES ('Yemen', '2');
INSERT INTO countries (name, continent_id) VALUES ('Turkey', '3');
INSERT INTO countries (name, continent_id) VALUES ('Albania', '3');
INSERT INTO countries (name, continent_id) VALUES ('Andorra', '3');
INSERT INTO countries (name, continent_id) VALUES ('Armenia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Austria', '3');
INSERT INTO countries (name, continent_id) VALUES ('Azerbaijan', '3');
INSERT INTO countries (name, continent_id) VALUES ('Belarus', '3');
INSERT INTO countries (name, continent_id) VALUES ('Belgium', '3');
INSERT INTO countries (name, continent_id) VALUES ('Bosnia and Herzegovina', '3');
INSERT INTO countries (name, continent_id) VALUES ('Bulgaria', '3');
INSERT INTO countries (name, continent_id) VALUES ('Croatia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Cyprus', '3');
INSERT INTO countries (name, continent_id) VALUES ('Czechia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Denmark', '3');
INSERT INTO countries (name, continent_id) VALUES ('Estonia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Finland', '3');
INSERT INTO countries (name, continent_id) VALUES ('France', '3');
INSERT INTO countries (name, continent_id) VALUES ('Georgia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Germany', '3');
INSERT INTO countries (name, continent_id) VALUES ('Greece', '3');
INSERT INTO countries (name, continent_id) VALUES ('Hungary', '3');
INSERT INTO countries (name, continent_id) VALUES ('Iceland', '3');
INSERT INTO countries (name, continent_id) VALUES ('Ireland', '3');
INSERT INTO countries (name, continent_id) VALUES ('Italy', '3');
INSERT INTO countries (name, continent_id) VALUES ('Latvia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Liechtenstein', '3');
INSERT INTO countries (name, continent_id) VALUES ('Lithuania', '3');
INSERT INTO countries (name, continent_id) VALUES ('Luxembourg', '3');
INSERT INTO countries (name, continent_id) VALUES ('Macedonia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Malta', '3');
INSERT INTO countries (name, continent_id) VALUES ('Moldova', '3');
INSERT INTO countries (name, continent_id) VALUES ('Monaco', '3');
INSERT INTO countries (name, continent_id) VALUES ('Montenegro', '3');
INSERT INTO countries (name, continent_id) VALUES ('Netherlands', '3');
INSERT INTO countries (name, continent_id) VALUES ('Norway', '3');
INSERT INTO countries (name, continent_id) VALUES ('Poland', '3');
INSERT INTO countries (name, continent_id) VALUES ('Portugal', '3');
INSERT INTO countries (name, continent_id) VALUES ('Romania', '3');
INSERT INTO countries (name, continent_id) VALUES ('San Marino', '3');
INSERT INTO countries (name, continent_id) VALUES ('Serbia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Slovakia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Slovenia', '3');
INSERT INTO countries (name, continent_id) VALUES ('Spain', '3');
INSERT INTO countries (name, continent_id) VALUES ('Sweden', '3');
INSERT INTO countries (name, continent_id) VALUES ('Switzerland', '3');
INSERT INTO countries (name, continent_id) VALUES ('Ukraine', '3');
INSERT INTO countries (name, continent_id) VALUES ('United Kingdom', '3');
INSERT INTO countries (name, continent_id) VALUES ('Vatican City', '3');
INSERT INTO countries (name, continent_id) VALUES ('Antigua and Barbuda', '4');
INSERT INTO countries (name, continent_id) VALUES ('Bahamas', '4');
INSERT INTO countries (name, continent_id) VALUES ('Barbados', '4');
INSERT INTO countries (name, continent_id) VALUES ('Belize', '4');
INSERT INTO countries (name, continent_id) VALUES ('Canada', '4');
INSERT INTO countries (name, continent_id) VALUES ('Costa Rica', '4');
INSERT INTO countries (name, continent_id) VALUES ('Cuba', '4');
INSERT INTO countries (name, continent_id) VALUES ('Dominica', '4');
INSERT INTO countries (name, continent_id) VALUES ('Dominican Republic', '4');
INSERT INTO countries (name, continent_id) VALUES ('El Salvador', '4');
INSERT INTO countries (name, continent_id) VALUES ('Grenada', '4');
INSERT INTO countries (name, continent_id) VALUES ('Guatemala', '4');
INSERT INTO countries (name, continent_id) VALUES ('Haiti', '4');
INSERT INTO countries (name, continent_id) VALUES ('Honduras', '4');
INSERT INTO countries (name, continent_id) VALUES ('Jamaica', '4');
INSERT INTO countries (name, continent_id) VALUES ('Mexico', '4');
INSERT INTO countries (name, continent_id) VALUES ('Nicaragua', '4');
INSERT INTO countries (name, continent_id) VALUES ('Panama', '4');
INSERT INTO countries (name, continent_id) VALUES ('Saint Kitts and Nevis', '4');
INSERT INTO countries (name, continent_id) VALUES ('Saint Lucia', '4');
INSERT INTO countries (name, continent_id) VALUES ('Saint Vincent and the Grenadines', '4');
INSERT INTO countries (name, continent_id) VALUES ('Trinidad and Tobago', '4');
INSERT INTO countries (name, continent_id) VALUES ('United States', '4');
INSERT INTO countries (name, continent_id) VALUES ('Australia', '5');
INSERT INTO countries (name, continent_id) VALUES ('Fiji', '5');
INSERT INTO countries (name, continent_id) VALUES ('Kiribati', '5');
INSERT INTO countries (name, continent_id) VALUES ('Marshall Islands', '5');
INSERT INTO countries (name, continent_id) VALUES ('Micronesia', '5');
INSERT INTO countries (name, continent_id) VALUES ('Nauru', '5');
INSERT INTO countries (name, continent_id) VALUES ('New Zealand', '5');
INSERT INTO countries (name, continent_id) VALUES ('Palau', '5');
INSERT INTO countries (name, continent_id) VALUES ('Papua New Guinea', '5');
INSERT INTO countries (name, continent_id) VALUES ('Samoa', '5');
INSERT INTO countries (name, continent_id) VALUES ('Solomon Islands', '5');
INSERT INTO countries (name, continent_id) VALUES ('Tonga', '5');
INSERT INTO countries (name, continent_id) VALUES ('Tuvalu', '5');
INSERT INTO countries (name, continent_id) VALUES ('Vanuatu', '5');
INSERT INTO countries (name, continent_id) VALUES ('Argentina', '6');
INSERT INTO countries (name, continent_id) VALUES ('Bolivia', '6');
INSERT INTO countries (name, continent_id) VALUES ('Brazil', '6');
INSERT INTO countries (name, continent_id) VALUES ('Chile', '6');
INSERT INTO countries (name, continent_id) VALUES ('Colombia', '6');
INSERT INTO countries (name, continent_id) VALUES ('Ecuador', '6');
INSERT INTO countries (name, continent_id) VALUES ('Guyana', '6');
INSERT INTO countries (name, continent_id) VALUES ('Paraguay', '6');
INSERT INTO countries (name, continent_id) VALUES ('Peru', '6');
INSERT INTO countries (name, continent_id) VALUES ('Suriname', '6');
INSERT INTO countries (name, continent_id) VALUES ('Uruguay', '6');
INSERT INTO countries (name, continent_id) VALUES ('Venezuela', '6');
INSERT INTO skill_levels (name) VALUES ('Beginner');
INSERT INTO skill_levels (name) VALUES ('Intermediate');
INSERT INTO skill_levels (name) VALUES ('Advanced');
INSERT INTO skill_levels (name) VALUES ('Professional');
INSERT INTO skill_levels (name) VALUES ('Extreme')
